1.单线程改并发; 2.内存优化
openGemini/data-migration-tools pull request #11
Opened 2023-06-03 12:05 UTC by wubin1989

2023-06-03 12:06 UTC, wubin1989 commented
#10

2023-06-05 03:35 UTC, shilinlee requested changes

2023-06-05 03:35 UTC, shilinlee commented on src/geminiservice.go
> +		Addr: "http://localhost:8086",
openGemini service address is not necessarily `localhost`

2023-06-05 03:45 UTC, shilinlee approved these changes

2023-06-05 03:46 UTC, merged