columns will be assembled into rows
openGemini/data-migration-tools pull request #5
Opened 2023-05-11 13:38 UTC by flaggyellow

feat: when migrating data, columns are assembled into rows before being written

2023-05-16 01:42 UTC, xiangyu5632 commented on src/dataMigrate_test.go
> +	"fmt"
please set the tab with 4 blank and reformat all files

2023-05-16 01:42 UTC, xiangyu5632 commented on src/cursor.go
> +package main
Please add the Apache license statement to the file header. 
by the way, if you reference some other open-source projects' source code,  we need to describe the code come from  and the modified part by ourself (like dataMirgarte.go)，**this new file‘s copyright set to yourself**

2023-05-16 02:17 UTC, flaggyellow commented on src/cursor.go
> +package main
Sure, I'll deal with it.

2023-05-16 11:08 UTC, shilinlee requested changes

2023-05-16 11:08 UTC, shilinlee commented on src/cursor.go
> +func (c *Cursor) init(st int64) error {
`st` is unused variable

2023-05-17 08:21 UTC, shilinlee approved these changes

2023-05-17 08:22 UTC, merged